name: CI

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run the build php script
      run: |
        echo "hola mundo" > version
    - name: Commit files 
      run: |
        git config --local user.name "Francisco Fuentes"
        git config --local user.email "contacto@francisco-fuentes.cl"
        git add version
        git commit -m "Actualizacion de version"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true