name: CI

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - uses: actions-ecosystem/action-get-latest-tag@v1
      id: get-latest-tag

    - name: get value in file
      id: version-file
      run: |
        echo "VERSIONFILE=$(cat version)" >> $GITHUB_ENV
      

    - name: Set env
      run: echo "TAG=${{ steps.get-latest-tag.outputs.tag }}" >> $GITHUB_ENV

    - name: Test
      run: |
        echo $TAG
        echo ${{ env.TAG }}
        echo $VERSIONFILE

    - name: Crear archivo version
      run: |
        echo '${{ env.TAG }}' > version
        echo $${{ env.TAG }} != $${{ env.VERSIONFILE }}

    - name: Commit files 
      if: $${{ env.TAG }} != $${{ env.VERSIONFILE }}
      run: |
        git config --local user.name "Francisco Fuentes"
        git config --local user.email "contacto@francisco-fuentes.cl"
        git add version
        git commit -m "Actualizacion de version"
  
    - name: Push changes
      if: $${{ env.TAG }} != $${{ env.VERSIONFILE }}
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true