name: CI

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - uses: actions-ecosystem/action-get-latest-tag@v1
      id: get-latest-tag

    - name: test2
      run: echo '{{ steps.get-latest-tag.outputs }}'

    - name: Set env
      run: echo "TAG=1.1.0" > $GITHUB_ENV
      #run:  git tag | sort -V | tail -1 > $GITHUB_ENV

    - name: Test
      run: |
        echo $TAG
        echo ${{ env.TAG }}

    - name: Crear archivo version
      run: |
        echo '${{ env.TAG }}' > version

    - name: Commit files 
      run: |
        git config --local user.name "Francisco Fuentes"
        git config --local user.email "contacto@francisco-fuentes.cl"
        git add version
        git commit -m "Actualizacion de version"
  
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true