name: CI

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions-ecosystem/action-release-label@v1
        id: release-label
        if: ${{ github.event.pull_request.merged == true }}

    - uses: actions-ecosystem/action-get-latest-tag@v1
      id: get-latest-tag
      if: ${{ steps.release-label.outputs.level != null }}

    - uses: actions/checkout@v2
    - name: Crear archivo version
      run: |
        echo '${{ steps.get-latest-tag.outputs.tag }}'
        echo '${{ steps.get-latest-tag.outputs.tag }}' > version

    - name: Commit files 
      run: |
        git config --local user.name "Francisco Fuentes"
        git config --local user.email "contacto@francisco-fuentes.cl"
        git add version
        git commit -m "Actualizacion de version"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true